# Generated by Django 5.2.5 on 2025-08-21 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_skill_remove_employee_created_at_and_more"),
        ("workplaces", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workplace",
            options={
                "ordering": ["desk_number"],
                "verbose_name": "Рабочее место",
                "verbose_name_plural": "Рабочие места",
            },
        ),
        migrations.RemoveField(
            model_name="workplace",
            name="location",
        ),
        migrations.RemoveField(
            model_name="workplace",
            name="name",
        ),
        migrations.AddField(
            model_name="workplace",
            name="desk_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Номер стола",
            ),
        ),
        migrations.AddField(
            model_name="workplace",
            name="employee",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workplace",
                to="employees.employee",
                verbose_name="Сотрудник",
            ),
        ),
        migrations.AlterField(
            model_name="workplace",
            name="description",
            field=models.TextField(
                blank=True, verbose_name="Дополнительная информация"
            ),
        ),
    ]
