# Generated by Django 5.2.5 on 2025-08-21 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название навыка"),
                ),
            ],
            options={
                "verbose_name": "Навык",
                "verbose_name_plural": "Навыки",
            },
        ),
        migrations.RemoveField(
            model_name="employee",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="email",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="hire_date",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="position",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="workplace",
        ),
        migrations.AddField(
            model_name="employee",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Мужской"), ("F", "Женский"), ("O", "Другой")],
                max_length=1,
                null=True,
                verbose_name="Пол",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="middle_name",
            field=models.CharField(blank=True, max_length=50, verbose_name="Отчество"),
        ),
        migrations.AddField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.CreateModel(
            name="EmployeeSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                            (8, "8"),
                            (9, "9"),
                            (10, "10"),
                        ],
                        verbose_name="Уровень навыка",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.employee",
                        verbose_name="Сотрудник",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.skill",
                        verbose_name="Навык",
                    ),
                ),
            ],
            options={
                "verbose_name": "Навык сотрудника",
                "verbose_name_plural": "Навыки сотрудников",
                "unique_together": {("employee", "skill")},
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                through="employees.EmployeeSkill",
                to="employees.skill",
                verbose_name="Навыки",
            ),
        ),
    ]
