# Generated by Django 5.2.5 on 2025-11-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_alter_employee_middle_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="middle_name",
            field=models.CharField(blank=True, max_length=50, verbose_name="Отчество"),
        ),
    ]
